
- name: Install Mosquitto GPG Key
  become: True
  become_user: root
  apt_key:  url=http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key state=present

- name: Add Mosquitto Repository
  become: True
  become_user: root
  apt_repository: repo='deb http://repo.mosquitto.org/debian stretch main'

- name: Install Mosquitto
  become: True
  become_user: root
  apt: name={{ item }}
  with_items:
      - mosquitto
      - mosquitto-clients
