---
# tasks file for kfieldho.influx
#

- name: Install Mosquitto Apt Dependencies
  become: True
  become_user: root
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      - build-essential
      - git
      - libwebsockets-dev
      - libc-ares-dev
      - uuid-dev
      - xsltproc
      - docbook-xsl

- name: Create mosquitto group
  become: True
  become_user: root
  group:
    name: mosquitto
    state: present

- name: Create mosquitto user
  become: True
  become_user: root
  user:
    name: mosquitto
    state: present
    createhome: True
    group: mosquitto
    shell: /bin/bash
    skeleton: False


- name: Fetch Mosquitto Git Repo
  git:
    repo: "{{ mosquitto_repo }}"
    dest: "{{ ansible_env.HOME }}/mosquitto"
    version: "{{ mosquitto_version }}"


- name: Build Mosquitto
  make:
  args:
    chdir: "{{ ansible_env.HOME }}/mosquitto"
    params:
      WITH_WEBSOCKETS: yes

- name: Install Mosquitto
  become: True
  become_user: root
  make:
  args:
    chdir: "{{ ansible_env.HOME }}/mosquitto"
    target: install

- name: Copy over configuration file
  become: True
  become_user: root
  when: not (mosquitto_config_file == "")
  copy:
    src: "{{ mosquitto_config_file }}"
    dest: /etc/mosquitto/mosquitto.conf

- name: Install Mosquitto Systemd Configuration
  become: True
  become_user: root
  copy:
    content: |
      [Unit]
      Description=Mosquitto MQTT Broker daemon
      ConditionPathExists=/etc/mosquitto/mosquitto.conf
      After=network.target
      Requires=network.target

      [Service]
      Type=forking
      RemainAfterExit=no
      StartLimitInterval=0
      PIDFile=/var/run/mosquitto.pid
      ExecStart=/bin/sh -c "/usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf -d"
      ExecReload=/bin/kill -HUP $MAINPID
      Restart=on-failure
      RestartSec=2

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/mosquitto.service

- name: Enable Mosquitto Service
  become: True
  become_user: root
  systemd: name=mosquitto.service enabled=true state=started daemon_reload=true
